/// posts
###

GET http://localhost:3000/post

###

GET http://localhost:3000/post?sender=4

###

GET http://localhost:3000/post/6963bc1c1b636f331dae94a4

###
POST http://localhost:3000/post
Content-Type: application/json  

{
  "text": "new post hereee",
  "img": "image_url",
  "sender": "4"
}

###
DELETE http://localhost:3000/post/6963bc121b636f331dae949d


###
PUT http://localhost:3000/post/6963bc1c1b636f331dae94a4
Content-Type: application/json  

{
  "text": "Inception22",
  "img": "image_url_updated"
}


/// comments

###

GET http://localhost:3000/comment

###

GET http://localhost:3000/comment?postId=6963bc1c1b636f331dae94a4

###

GET http://localhost:3000/comment/6963c030256d36272310d8ce

###
POST http://localhost:3000/comment
Content-Type: application/json

{
  "postId": "6963c025256d36272310d8cc",
  "sender": "12",
  "message": "why????"
}

###
DELETE http://localhost:3000/comment/6963bfea256d36272310d8c3


###
PUT http://localhost:3000/comment/6963c030256d36272310d8ce
Content-Type: application/json

{
  "message": "Updated message"
}